type: array
description: Section containing data of the ordered products. Section <code>products</code> is an array of objects of type product.
items:
    type: object
    required: [name, unitPrice, quantity]
    properties:
        name:
            type: string
            description: Name of the product.
            example: My product
        unitPrice:
            type: string
            description: Unit price.
            example: 999
        quantity:
            type: string
            description: Quantity of given product
            example: 4
        virtual:
            type: boolean
            description: Product type, which can be virtual or material.
            example: true
        listingDate:
            type: string
            format: '2019-03-27T10:57:59.000+01:00'
            description: Marketplace date from which the product (or offer) is available, ISO format applies.
            example: 2019-03-27T10:57:59.000+01:00
